export enum NotificationType {
  WALLET_CREDITED = 'wallet_credited',
  WALLET_DEBITED = 'wallet_debited',
  PAYMENT_RECEIVED = 'payment_received',
  PAYMENT_FAILED = 'payment_failed',
  PAYMENT_APPROVED = 'payment_approved',
  PAYMENT_SUCCESSFUL = 'payment_successful',
  SUBSCRIPTION_CREATED = 'subscription_created',
  SUBSCRIPTION_EXPIRED = 'subscription_expired',
  SUBSCRIPTION_EXPIRING = 'subscription_expiring',
  PLAN_UPGRADED = 'plan_upgraded',
  PLAN_DOWNGRADED = 'plan_downgraded',
  PLAN_LIMIT_UPDATED = 'plan_limit_updated',
  LOGIN_ATTEMPT = 'login_attempt',
  ACCOUNT_UPDATED = 'account_updated',
  ROLE_UPDATED = 'role_updated',
}
